---
- name: Restart AI Worker service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ horde_regen_worker_service_name }}"
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[horde_regen_worker_username].1 }}"
  become: true
  become_user: "{{ horde_regen_worker_username }}"
  when: not (horde_regen_worker_service_started is defined and horde_regen_worker_service_started.changed | default(false))
  tags:
    - worker
    - systemd
