---
- name: Restart AI Worker service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ worker_service_name }}"
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[worker_username].1 }}"
  become: true
  become_user: "{{ worker_username }}"
  when: not service_started.changed
  tags:
    - worker
    - systemd
